dataset: "dunnhumby"
seed: 2025
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]

eval_args:
  group_by: user
  order: TO
  split:
    RS: [0.8, 0.2, 0.0]

metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 100
valid_metric: recall@100

embedding_size: 384
hidden_size: 384
