# dataset config
dataset: ml-10m
seed: 2025
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
TIME_FIELD: timestamp



metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 100
valid_metric: mrr@100

hidden_size: 256
gpu_id: 0



load_col:
    inter: [user_id, item_id, rating, timestamp]
val_interval:
    rating: "[3,inf)"
unused_col: 
    inter: [rating]


user_inter_num_interval: "[10,inf)"

eval_args:
  group_by: user
  order: TO
  split: 
    RS: [0.8, 0.2, 0.0]


