# Model configuration
model: LightGCN

# Training configuration
epochs: 1000
train_batch_size: 4096
eval_batch_size: 4096000
learning_rate: 0.001
weight_decay: 1e-5
early_stopping: 10

# Model-specific hyperparameters
embedding_size: 384
n_layers: 3
reg_weight: 1e-4